# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos6.4.x86_64"

  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  # workaround for windows error
  # see http://blog.cles.jp/item/5698
  Encoding.default_external = 'UTF-8'

  #config.vm.provision "shell" , path: "setup.sh"

  config.vm.network :private_network, ip: "10.10.10.10"
  config.vm.network :forwarded_port, guest: 3306, host: 8806
  config.vm.synced_folder "./", "/home/samba", owner: 'vagrant', group: 'nginx', mount_options: ['dmode=777', 'fmode=666']
end
